### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by parion** [autoset-controller/controller#13]
Design a logo for autoset controller.

**Comment by ggcarlosr** [comment]
Hello brother I see that you have opened this Issue to request a logo for your app, I am a graphic designer and I can help the free code community for free.

**Comment by parion** [comment]
If you could design a logo for our automated platform system, that would be well appreciated. Open a PR, we'll review the logo, and credit you if we accept. 😄

**Comment by ggcarlosr** [comment]
Could you tell me in a general way what your app is about and if it has any color or shape that you would like it to be taken into account or you want the proposal to be free.

**Comment by parion** [comment]
@MDHollen Wanna take this one?

**Comment by MDHollen** [comment]
We're building a control system for motorized platforms and linear drivers, for use in theatrical automation. In the same vein as a control system like QLab (used for audio systems in theatre), a user can design and coordinate the actions taken by their motorized systems to move set pieces and/or carry actors around the stage space.

In terms of theme, we haven't determined a final plan for color, but the main design shapes we'll be using in the program would be the shape of the free-roaming platform (a short rectangular prism with hidden wheels) and arrows, which would show the path taken by the platform.

Thank you for offering your time and expertise! We look forward to seeing what you come up with.

**Comment by ggcarlosr** [comment]
friends trying to identify each way they indicate me I could make some sketches in the third option try to simplify everything but maybe you do not see the wheels well, of course this is nothing definitive neither in form nor in color just a brainstorming . 


![capture](https://user-images.githubusercontent.com/37964430/40571763-b960de00-606c-11e8-8371-302472d0f75d.png)

**Comment by MDHollen** [comment]
i like the direction you're taking with the third option! i'm not terribly worried about seeing the wheels - they're not visible on the actual platform either.

could you make some versions with horizontal bars, rather than vertical? that would match the layout of our program more closely.

**Comment by ggcarlosr** [comment]
Here several positions of the bars I think we can define some of these icons, the inclined distributed bars are better than vertically or horizontally. 

![capture](https://user-images.githubusercontent.com/37964430/40594917-d5e9c35e-61ff-11e8-85a8-6e17b8d99a82.png)
